// Code generated by MockGen. DO NOT EDIT.
// Source: update.go

// Package updatemock is a generated GoMock package.
package updatemock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockURLUpdater is a mock of URLUpdater interface.
type MockURLUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockURLUpdaterMockRecorder
}

// MockURLUpdaterMockRecorder is the mock recorder for MockURLUpdater.
type MockURLUpdaterMockRecorder struct {
	mock *MockURLUpdater
}

// NewMockURLUpdater creates a new mock instance.
func NewMockURLUpdater(ctrl *gomock.Controller) *MockURLUpdater {
	mock := &MockURLUpdater{ctrl: ctrl}
	mock.recorder = &MockURLUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLUpdater) EXPECT() *MockURLUpdaterMockRecorder {
	return m.recorder
}

// UpdateURL mocks base method.
func (m *MockURLUpdater) UpdateURL(urlToUpdate, oldAlias, newAlias string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateURL", urlToUpdate, oldAlias, newAlias)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateURL indicates an expected call of UpdateURL.
func (mr *MockURLUpdaterMockRecorder) UpdateURL(urlToUpdate, oldAlias, newAlias interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateURL", reflect.TypeOf((*MockURLUpdater)(nil).UpdateURL), urlToUpdate, oldAlias, newAlias)
}
